### ISSUE TITLE
API inconsistency in ECP.mul 

### ISSUE THREAD

**Issue by webmaster128** [miracl/amcl#11]
While `FP.mul`, `FP2.mul` and `BIG.imul`/`.pmul`/`.pxmul` multiply in-place, `ECP.mul`, `ECP2.mul`, `ECP4.mul`, `ECP8.mul` are not mutating the object. Is this intended?

This is very easy to get wrong I think, see e.g. [this code](https://gist.github.com/pyrros/4fddd7d49ae7c9c935f5d6a9a27d14c3) which does noops like

```js
var Y=new ECP();
Y.copy(ePK.z);
Y.mul(x.f);
```

all over the place.

**Comment by mcarrickscott** [comment]
Well yes, it is sort of intended, although I do take your point. Lower level functions perform better in-place, as their use discourages unnecessary data copying. But at a higher level program readability becomes more important, and code littered with the creation of copies becomes less readable. So z=x.add(y) is simpler than z=x; z.add(y);

**Comment by webmaster128** [comment]
Thanks for the feedback. I agree that the immutable multiplication of ECPs works much better for application level code. Right now, I don't have a great idea how to improve usability of the API in this case.
