### ISSUE TITLE
Go: main package prevents importing

### ISSUE THREAD

**Issue by manudrijvers** [miracl/amcl#2]
All the files of the go implementation are currently in a package main. This prevents importing the library: 
`can't load package: [...] import "github.com/miracl/amcl-go" is a program, not an importable package`

**Comment by mcarrickscott** [comment]
Hello Manu,


In fact AMCL is not really a self-contained library. But it contains the
components for a user to create such a library.

So the Java code is not bundled into a jar file, the rust code is not in a
crate, and the go code is not packaged.

It is expected that the consumer of the code will bundle it into whatever
jar/crate/package/library format that suits them and their particular
project.


Mike
