### ISSUE TITLE
Pairing function does not return 1 for P=infinity, Q=infinity

### ISSUE THREAD

**Issue by webmaster128** [miracl/amcl#24]
If I understood correctly, the pairing function `e` must return the neutral group element 1 for

* `e(P, 0)` for every P
* `e(0, Q)` for every Q

which implies that `e(0, 0) == 1` must be satisfied.

After https://github.com/miracl/amcl/commit/be9d80b89fe8359c3fab0e109f0f91d60b2c2527, the first two of the following tests work, the 3rd fails. Is this a bug?

```js
  it("satisfies e(P,0) == 1", () => {
    const P = g1.mul(new ctx.BIG(5));
    const Q = new ctx.ECP2();
    expect(ctx.PAIR.fexp(ctx.PAIR.ate(Q, P)).isunity()).toEqual(true);
  });

  it("satisfies e(0,Q) == 1", () => {
    const P = new ctx.ECP();
    const Q = g2.mul(new ctx.BIG(8));
    expect(ctx.PAIR.fexp(ctx.PAIR.ate(Q, P)).isunity()).toEqual(true);
  });

  it("satisfies e(0,0) == 1", () => {
    const P = new ctx.ECP();
    const Q = new ctx.ECP2();
    expect(ctx.PAIR.fexp(ctx.PAIR.ate(Q, P)).isunity()).toEqual(true);
  });
```

**Comment by mcarrickscott** [comment]
Good point. The case e(O,O) evaluates very naturally as 0. But mathematically it seems it should be 1. This will require an explicit test for this case. I would love a pointer to a maths text which explicitly states that e(O,O)=1 (indeed for a type 1 pairing e(P,P) !=1 is actually an explicit condition for non-degeneracy).

**Comment by webmaster128** [comment]
I came across this property when implementing Groth-Sahai proofs. In https://eprint.iacr.org/2007/155, version 20160411:065033, page 25 in "Common reference string" and "Pairing product equations" it is assumed that `e(0, 0) == 1` (in the top left component of the result of `F`).

In https://www.math.uwaterloo.ca/~ajmeneze/publications/pairings.pdf 2.1 it says (at least for symmeteric pairings):

> The following properties of bilinear pairings can be easily verified. [...] For all S, T ∈ G1 
> (1) e(S,∞) = 1 and e(∞, S) = 1.

and I guess should also be true for `S = ∞`.

**Comment by mcarrickscott** [comment]
Yes, I will change it. It seems the simplest thing to do is to return 1 if the ECP point P is infinity.

**Comment by mcarrickscott** [comment]
Fixed

**Comment by webmaster128** [comment]
Thanks a lot, works fine now (tested via PAIR.js). For future visitors: this was fixed in https://github.com/miracl/amcl/commit/7c2262077f2348aa0e4901ba94b7cc4f1211b6fc
