### ISSUE TITLE
[rustnew and rust] Something wrong with transform function

### ISSUE THREAD

**Issue by MRJCrunch** [miracl/amcl#4]
I've tried to use rust and rustnew libraries and had faced this error during execution of key_pair function from rsa.rs module. This is a stack trace:
thread 'main' panicked at 'attempt to add with overflow', amcl/hash256.rs:85
stack backtrace:
   1:     0x556b4dfa07ca - std::sys::imp::backtrace::tracing::imp::write::h3188f035833a2635
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x556b4dfa26ff - std::panicking::default_hook::{{closure}}::h6385b6959a2dd25b
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:349
   3:     0x556b4dfa22fe - std::panicking::default_hook::he4f3b61755d7fa95
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:365
   4:     0x556b4dfa2ae7 - std::panicking::rust_panic_with_hook::hf00b8130f73095ec
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:553
   5:     0x556b4dfa2924 - std::panicking::begin_panic::h6227f62cb2cdaeb4
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:515
   6:     0x556b4dfa2899 - std::panicking::begin_panic_fmt::h173eadd80ae64bec
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:499
   7:     0x556b4dfa2827 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:475
   8:     0x556b4dfc861d - core::panicking::panic_fmt::h3b2d1e30090844ff
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/panicking.rs:69
   9:     0x556b4dfc8554 - core::panicking::panic::h2596388ccef1871c
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/panicking.rs:49
  10:     0x556b4df89d4a - amcl::hash256::HASH256::transform::h57df235901f556e6
                        at <path>/amcl/hash256.rs:85
  11:     0x556b4df8a268 - amcl::hash256::HASH256::process::h4ed21b1141b5a224
                        at <path>/amcl/hash256.rs:128
  12:     0x556b4df8ac0b - amcl::rand::RAND::fill_pool::hfa04a3ef42ec8e1d
                        at <path>/amcl/rand.rs:90
  13:     0x556b4df8ae04 - amcl::rand::RAND::getbyte::h5fb73e9f80a50c7c
                        at <path>/amcl/rand.rs:127
  14:     0x556b4df8ef85 - amcl::rsa2048::big::BIG::random::hc1c3e3e0d3e74725
                        at <path>/amcl/rsa2048/big.rs:635
  15:     0x556b4df981cf - amcl::rsa2048::ff::FF::random::hdc0f320ef509041e
                        at <path>/amcl/rsa2048/ff.rs:712
  16:     0x556b4df99e62 - amcl::rsa2048::rsa::key_pair::h0e4b12e406a7943e
                        at <path>/amcl/rsa2048/rsa.rs:94
  17:     0x556b4df877e9 - <myfunction>::hf1b1d63f6f0d0c33
                        at <path>/src/prover.rs:20
  18:     0x556b4df8795f - <myfunction>::hf6e363d8b82db0f0
                        at <path>/src/prover.rs:28
  19:     0x556b4df87152 - main::h532d1f955353f621
                        at <path>/src/main.rs:7
  20:     0x556b4dfaa40a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  21:     0x556b4dfa2fe6 - std::rt::lang_start::h65647f6e36cffdae
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:434
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panic.rs:351
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/rt.rs:57
  22:     0x556b4df871d2 - main
  23:     0x7fe069eaa82f - __libc_start_main
  24:     0x556b4df86bf8 - _start
  25:                0x0 - <unknown>

**Comment by mcarrickscott** [comment]
The significant information in the error message is "attempt to add with
overflow".

Rust unlike most other languages by default can generate a run-time error
on integer overflow. Unfortunately some standard crypto functions like
hash256 depend on integer overflow, the behaviour of which is well
understood. For example adding the byte 255 to the byte 1 results in the
byte 0. The "true" answer is of course 256, but that's an overflow of 8
bits.

So to get the code to build, error generation on integer overflow must be
turned off. The simplest way to do this is to build in release mode (and
not in debug mode).

http://huonw.github.io/blog/2016/04/myths-and-legends-about-integer-overflow-in-rust/


Mike

**Comment by MRJCrunch** [comment]
Thank you!

**Comment by vimmerru** [comment]
Can this code be implemented with wrapping_* functions of std lib? Panic in debug makes this library very hard to use within cargo based development workflow.

**Comment by mcarrickscott** [comment]
Yes, good idea, this should be done.

Check back in a couple of weeks...


Mike
