### ISSUE TITLE
bls.js and bls256.js don't load in IE 11

### ISSUE THREAD

**Issue by mhewett-ks** [miracl/amcl#42]
```
SCRIPT1003: Expected ':'
bls.js (73,18)
SCRIPT1003: Expected ':'
bls256.js (73,18)
```

These files define a few functions in the form:
```
        bls_hashit: function(m) {
```

Then switch to just declaring a function:
```
	KeyPairGenerate(rng,S,W) {
```

I'm not sure how that even works in other browsers since it is in the body of an object.

All of the other .js files are loading with no errors.

**Comment by mcarrickscott** [comment]
Good catch, thanks. Fixed.
