### ISSUE TITLE
Problem compiling without __int128

### ISSUE THREAD

**Issue by nizkp** [miracl/amcl#6]
Hello,
I compiled milagro-crypto-c to WebAssembly, and it works almost out of the box (and is very fast, BTW). Just had to remove the
```c
#define dchunk __int128
```
Then I tried the same with amcl (BTW, not sure which one of the two libraries I should use) and it seems that the 64 bit compilation will not work. I think the problem is in big_XXX.h, the fallback `chunk_muladd` when `dchunk` is not defined uses the `HMASK` variable, but it seems to be undefined. The 32 bit compilation works fine though, because there `dchunk` is defined.

I guess I can still use milagro-crypto-c instead, but just wanted to let you know that compilation breaks in this case, and by looking at the code I think the intention is to handle it too.

Thanks,

**Comment by mcarrickscott** [comment]
I think I see the problem. In two places in muladd HMASK should be HMASK_XXX

Thanks!

Mike

**Comment by nizkp** [comment]
I though so, but was not sure because in milagro-crypto-c I saw two different ones (HMASK and HMASK1).

Anyway, thanks!
