### ISSUE TITLE
Problem using Brainpool elliptic curve (actually interested in brainpoolP256r1 curve)

### ISSUE THREAD

**Issue by JunSunRyu** [miracl/amcl#7]
Hello!

I'm trying to use NIST P-256 and BRAINPOOL elliptic curves with AMCL3.
In case of NIST P-256 elliptic curve, it work properly creating a correct pair key.
However, in case of BRAINPOOL elliptic curve, it's not properly working. it is creating something wrong pair key.

I checked the key is wrong using openSSL and cycloneCrypto libraries.

Here are some STEPs what I did to check a generated pair key.
1. Change private key generation code of cycloneCrypto library from random number to static number.
2. Get a key pair using openSSL library.
    1) For NIST P-256 curve
    openssl ecparam -name prime256v1 -genkey > ecprivkey.pem
    openssl ec -in ecprivkey.pem -text -noout
    2) For BrainpoolP256r1 curve
    openssl ecparam -name brainpoolP256r1 -genkey > ecprivkey.pem
    openssl ec -in ecprivkey.pem -text -noout
3. Take private keys according to NIST and Brainpool curves and give the keys as input value for private key of cycloneCrypto library. ( I checked private key and public key pair for each curve.  The value was exactly same with the key values from openSSL library. So I realized it is correctly working.)
4. Get key pairs for NIST curve and Brainpool curve from AMCL3 library.
5. Take the private keys and give the keys as input value for private key of cycloneCrypto library. ( In this case, NIST curve is working correctly making same key pair values. However, the value for BRAINPOOL was different. )

Please check it. I hope to know what's matter with Brainpool curve.

**Comment by mcarrickscott** [comment]
Hello,

I think I see the problem. The Brainpool curves are specified with a random
A parameter.

y^2=x^3+Ax+B

 However it is well known that Weierstrass curves are more efficient if
A=-3.

Y^2=X^3-3X+B'

The proposers of Brainpool were aware of this, and made sure that their
curves could be transformed to an isomorphic form, with A=-3. The
assumption was that implementors (like you!) might want to convert to this
more efficient form, do the elliptic curve calculations on the A=-3 curve,
and then convert the result back to the original curve.

See https://tools.ietf.org/html/rfc5639#page-11

Section 2.2, Note 3.

Now the AMCL library is written with the assumption that A=-3 (or A=0). So
the curve must be transformed in this way to work with AMCL.

What all this means is that points (x,y) on the original curve must first
be transformed to points (X,Y) on the new curve, where X=Z^2.x and Y=Z^3.y,
before using with AMCL.  After the curve calculation, to convert back if
you need to, x=X/Z^2 and y=Y/Z^3. All calculations modulo p.

For your convenience I have worked out the Z used in this case

Z="3E2D4BD9597B58639AE7AA669CAB9837CF5CF20A2C852D10F655668DFC150EF0";

This is a 4th root modulo p of of (-3/A)


Mike

**Comment by JunSunRyu** [comment]
Hello,

Thank you for your reply.
I'll check about the points (X,Y) and the value before using with AMCL.
If you give me the exact value about the points (X,Y), I think I can be more convenience. ;-) 

Anyway, after written the open issue, I checked the curve values in "rom_curve_BRAINPOOL.c", rom_field_BRAINPOOL.c, rom_field_NIST256.c, and "rom_curve_NIST256.c" files comparing with the values in cyclone library. I converted the values in cyclone library to BIG_256_28 values using the BIG_256_28_fromBytes() function in AMCL library.

Then, I realized that the values, such as CURVE_B_NIST256, CURVE_Order_NIST256, CURVE_Gx_NIST256, CURVE_Gy_NIST256, and Modulus_NIST256, are exactly same with the curve values in cyclone library.
However, in case Brainpool, CURVE_Order_BRAINPOOL and Modulus_BRAINPOOL values are same with the values in cyclone library. the values - CURVE_B_BRAINPOOL, CURVE_Gx_BRAINPOOL, and CURVE_Gy_BRAINPOOL - are different from them in cyclone library.
So, I got below values and I am trying to use the below values instead of original values in AMCL3.
=========================================================================
const BIG_256_28 CURVE_B_BRAINPOOL=     {0x0F8C07B6,0x0CCDC18F,0x07E1CE6B,0x016295CF,0x0CBF9584,0x0D9BBD77,0x04F330B5,0x0E94A4B4,0x06DC5C6C,0x00000002};
const BIG_256_28 CURVE_Order_BRAINPOOL= {0x074856A7,0x01E0E829,0x01A6F790,0x07AA3B56,0x0D718C39,0x0909D838,0x0C3E660A,0x0A1EEA9B,0x09FB57DB,0x0000000A};
const BIG_256_28 CURVE_Gx_BRAINPOOL=    {0x0ACE3262,0x04453BD9,0x0D23C23A,0x027E1E3B,0x07AFB9DE,0x02FFC81B,0x0B2C4B48,0x0CB7E57C,0x0BD2AEB9,0x00000008};
const BIG_256_28 CURVE_Gy_BRAINPOOL=    {0x0F046997,0x01D54C72,0x0D8E545C,0x045132DE,0x0DC9C277,0x01A14611,0x0D97F846,0x0C3DAC4F,0x047EF835,0x00000005};

const BIG_256_28 Modulus_BRAINPOOL= {0xF6E5377,0x13481D1,0x6202820,0xF623D52,0xD726E3B,0x909D838,0xC3E660A,0xA1EEA9B,0x9FB57DB,0xA};
=========================================================================

And, some things I wondering are about the values such as MConst_BRAINPOOL and R2modp_BRAINPOOL. I hope to know about what are exact values for these and about how to get the values.

Honestly, I hope to get the exact values about CURVE_A_BRAINPOOL, CURVE_B_I_BRAINPOOL, CURVE_B_BRAINPOOL, CURVE_Order_BRAINPOOL, CURVE_Gx_BRAINPOOL, CURVE_Gy_BRAINPOOL, Modulus_BRAINPOOL, R2modp_BRAINPOOL, and MConst_BRAINPOOL for BrainpoolP256r1 curve from YOU.

James Ryu

**Comment by mcarrickscott** [comment]
Hello,


Yes of course we could send you the exact values for the Brainpool 256r1
curve, but they would not work with the AMCL library.

You will have noticed that in the AMCL ROM files for the curve...

const int CURVE_A_BRAINPOOL= -3;

For the curve 256r1 the 256-bit A value is far too large to fit inside of a
32 or 64 bit int. Therefore the original Brainpool 256r1 parameters will
not work with the AMCL library.

The short answer to your original question (and the one I should have
given) would have been to point out that the AMCL library supports only the
Brainpool 256t1 curve, referred to in the standards as the "twisted" curve.

You will note from the standards document  https://tools.ietf.org/html/rf
c5639#page-11 that for 256t1

 p =  A9FB57DBA1EEA9BC3E660A909D838D726E3BF623D52620282013481D1F6E5377


 A =  A9FB57DBA1EEA9BC3E660A909D838D726E3BF623D52620282013481D1F6E5374



Observe that A=p-3!. This is what AMCL expects and assumes.

All other popular standardized Weierstrass curves I am aware of use A=-3.


However, as I was trying to point out in my last email, curves 256r1 and
256t1 are essentially the SAME curve! They are isomorphic. A simple linear
transformation converts from one form to the other and back again.

Using A=-3 leads to a faster point doubling formula. Therefore in ALL cases
it makes sense if using 256r1 to

(a) convert the input points to work with 256t1
(b) do the calculations on 256t1
(c) Convert the results back to 256r1

Of course its a lot simpler, and makes a lot more sense, to work with 256t1
directly.


Mike

**Comment by JunSunRyu** [comment]
Hello,

Thank you for your reply.

Honestly, It is difficult to figure out about how to make the functionality of the linear transformation to change from 256t1 to 256r1 for me because I'm not security guy but implementer using security core.

Also, I'm interested in ECDSA and ECIES.
Is it possible to get correct ECDSA and ECIES results even though  I got key pair for 256r1 converted from 256t1?

Thanks.

James Ryu

**Comment by mcarrickscott** [comment]
Hello,

From a security point of view the two curves are equivalent. So ideally you
should just always use 256t1. Points can be transferred between the two in
either direction using a simple linear non-secret transformation.

A key pair for 256r1 consists of P=sG, where G is a generator point, s is
the secret key and P is the public key. The private key is unaffected, the
public key P(x,y) can be moved to 256t1 as ( Z^2.x,Z^3.y). So if your only
problem is that the key pairs are generated on 256r1, then the "fix" is
relatively easy.

It is not our intention to support curves with A not equal to -3 or 0, as
it simply slows down the calculations and there is no security benefit.

Mike
